# Generated by Django 2.0.3 on 2018-05-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180514_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('catalog.can_author_edit', 'Can author edit'),)},
        ),
    ]
